export interface LocationCoordinates {
  latitude: number
  longitude: number
}
export interface LocationImage {
  type: string
  name: string
  uri: string
}

export interface TripForm {
  id: string
  name: string
  start_date: string
  end_date: string
  cover_photo: {
    uri: string
    name: string
    type: 'image' | 'video' | undefined
  }
  locations: TripFormLocation[]
}
export interface TripFormLocation {
  name: string
  trip_id: string
  coordinates: LocationCoordinates
  images: LocationImage[]
}

// Generated by https://quicktype.io

export interface NewTripForm {
  id: string
  name: string
  start_date: string
  end_date: string
  cover_photo: string
  created_at: string
  updated_at: string
}
