name: Continuous Integration

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review

jobs:
  lint-test:

    name: Lint and Test

    runs-on: ubuntu-latest

    if: ${{ github.event_name == 'push' || !github.event.pull_request.draft }}

    env:
      DB_HOST: 127.0.0.1

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'

      - name: Cache Node Modules
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.OS }}-npm-cache-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install JS Dependencies
        run: yarn

      - name: Lint application code
        run: yarn lint
